### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by waldandrade** [tuxetuxe/multitenant-connection-provider#2]
I'm using this to create my MultiTenant ... but i'm not undertanding very well.

The "databaseInitializer' is my problem .... i'm not 100% sure of what i need to put at 'initializeDatabase()' method.

**Comment by tuxetuxe** [comment]
Hi,

Th `initalizeDatabase` hook is supposed to be a way to dynamically bootstrap tenant databases. I.e. Somehow you configure a new tenant in your application, setup the proper database in the database server and, without any other action the application can create all the structure and data needed for that tenant.
Having said that, it is completely optional if you don't want to use it just return `null`.

BTW: I've updated the project and created a sample implementation located here -> https://github.com/tuxetuxe/multitenant-connection-provider-sample
